[build]
  root = "backend"
  builder = "NIXPACKS"

[build.env]
  PYTHON_VERSION = "3.11"

[deploy]
  startCommand = "./start.sh"

[env]
  ACCESS_TOKEN_EXPIRE_MINUTES = "1440"
  CORS_ORIGINS = "[\"https://anthony-sistem.netlify.app\"]"
  SECRET_KEY = "cambia_esta_clave_en_railway"

